# Generated by Django 5.2.16 on 2026-07-11 04:15

from django.db import migrations


PRODUCTS = [
    ("jordan-4-paris-olympics", "jordan", "Air Jordan 4 Retro SE Paris Olympics", 241000, "assets/img/shop/jordan423.png", ["38", "39", "40", "41", "42"]),
    ("jordan-4-military-black", "jordan", "Air Jordan 4 Retro Military Black", 240000, "assets/img/shop/jordan623.png", ["39", "40", "41", "42", "43"]),
    ("jordan-3-white-cobalt-bliss", "jordan", "Air Jordan 3 Retro White Cobalt Bliss", 230000, "assets/img/shop/jodan421.png", ["38", "39", "40", "41", "42"]),
    ("jordan-1-obsidian", "jordan", "Jordan 1 Obsidian", 240000, "assets/img/shop/jordanobsidian-card.png", ["38", "39", "40", "41", "42", "43"]),
    ("jordan-1-bordeaux", "jordan", "Air Jordan 1 High OG Bordeaux", 249000, "assets/img/shop/2634.png", ["39", "40", "41", "42", "43", "44"]),
    ("jordan-4-j-balvin", "jordan", "Jordan 4 J Balvin", 450000, "assets/img/shop/727340.png", ["38", "39", "40", "41", "42"]),
    ("adidas-forum-low-green-white", "adidas", "Adidas Forum Low Green / White", 190000, "assets/img/shop/Sin título (270 x 274 px) (5).png", ["38", "39", "40", "41", "42", "43"]),
    ("adidas-adizero-adios-pro", "adidas", "Adidas Adizero Adios Pro", 220000, "assets/img/shop/Sin título (270 x 274 px) (2).png", ["39", "40", "41", "42", "43"]),
    ("nike-air-force-1-triple-white", "nike", "Nike Air Force 1 Low Triple White", 230000, "assets/img/shop/Sin título (270 x 274 px) (3).png", ["38", "39", "40", "41", "42", "43"]),
    ("adidas-sl-72", "adidas", "Adidas SL 72", 195000, "assets/img/shop/Sin título (270 x 274 px) (1).png", ["38", "39", "40", "41", "42", "43"]),
    ("adidas-campus", "adidas", "Adidas Campus", 210000, "assets/img/shop/adidas.png", ["39", "40", "41", "42", "43", "44"]),
    ("puma-suede-classic", "puma", "Puma Suede Classic", 140000, "assets/img/shop/puma-suede-white.png", ["38", "39", "40", "41", "42", "43"]),
    ("puma-palermo", "puma", "Puma Palermo", 175000, "assets/img/shop/Sin título (270 x 274 px).png", ["38", "39", "40", "41", "42"]),
    ("nike-dunk-low-year-rabbit", "nike", "Nike Dunk Low Retro PRM Year of the Rabbit", 250000, "assets/img/shop/816619.png", ["38", "39", "40", "41", "42", "43"]),
    ("nike-sb-dunk-low-travis-scott", "nike", "Nike SB Dunk Low x Travis Scott Cactus Jack", 260000, "assets/img/shop/27734.png", ["38", "39", "40", "41", "42", "43"]),
    ("nike-calm-mule", "nike", "Nike Calm Mule", 180000, "assets/img/shop/Sin título (270 x 274 px) (4).png", ["38", "39", "40", "41", "42", "43"]),
]


def seed_products(apps, schema_editor):
    Product = apps.get_model("store", "Product")
    for slug, brand, name, price, image, sizes in PRODUCTS:
        Product.objects.update_or_create(
            slug=slug,
            defaults={
                "brand": brand,
                "name": name,
                "description": f"{name}, seleccionado por Juaco Store para estilo urbano y uso diario.",
                "price": price,
                "image": image,
                "sizes": sizes,
                "stock": 20,
                "is_active": True,
            },
        )


def unseed_products(apps, schema_editor):
    Product = apps.get_model("store", "Product")
    Product.objects.filter(slug__in=[item[0] for item in PRODUCTS]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [migrations.RunPython(seed_products, unseed_products)]
