# Generated by Django 5.2.16 on 2026-07-12 05:38

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_favorite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(editable=False, max_length=20, unique=True, verbose_name='número de pedido')),
                ('status', models.CharField(choices=[('pending', 'Pendiente de pago'), ('paid', 'Pagado'), ('shipped', 'Enviado'), ('delivered', 'Entregado'), ('cancelled', 'Cancelado')], db_index=True, default='pending', max_length=12, verbose_name='estado')),
                ('payment_method', models.CharField(choices=[('bank_transfer', 'Transferencia bancaria'), ('cash_on_delivery', 'Pago contra entrega'), ('bold', 'Pago con Bold')], default='bank_transfer', max_length=20, verbose_name='método de pago')),
                ('recipient_name', models.CharField(max_length=161, verbose_name='destinatario')),
                ('phone', models.CharField(max_length=30, verbose_name='teléfono')),
                ('address_line_1', models.CharField(max_length=180, verbose_name='dirección')),
                ('address_line_2', models.CharField(blank=True, max_length=180, verbose_name='complemento')),
                ('department', models.CharField(max_length=80, verbose_name='departamento')),
                ('city', models.CharField(max_length=80, verbose_name='ciudad')),
                ('postal_code', models.CharField(blank=True, max_length=12, verbose_name='código postal')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='subtotal')),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='costo de envío')),
                ('total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='total')),
                ('notes', models.TextField(blank=True, verbose_name='notas del pedido')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'pedido',
                'verbose_name_plural': 'pedidos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=180, verbose_name='producto')),
                ('product_image', models.CharField(blank=True, max_length=255, verbose_name='imagen')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='precio unitario')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='cantidad')),
                ('size', models.CharField(blank=True, max_length=12, verbose_name='talla')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='store.product')),
            ],
            options={
                'verbose_name': 'artículo del pedido',
                'verbose_name_plural': 'artículos del pedido',
            },
        ),
    ]
