# Generated by Django 5.2.16 on 2026-07-13 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_customerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='purchase_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='valor de compra'),
        ),
        migrations.AddField(
            model_name='order',
            name='sale_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='valor de venta'),
        ),
    ]
