# Generated by Django 5.2.16 on 2026-07-13 01:55

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_order_purchase_value_order_sale_value'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, verbose_name='nombre')),
                ('email', models.EmailField(max_length=254, verbose_name='correo')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='telefono')),
                ('subject', models.CharField(blank=True, max_length=180, verbose_name='asunto')),
                ('message', models.TextField(verbose_name='mensaje')),
                ('channel', models.CharField(default='Formulario web', max_length=30, verbose_name='canal')),
                ('status', models.CharField(choices=[('new', 'Nueva'), ('in_progress', 'En proceso'), ('resolved', 'Resuelta')], db_index=True, default='new', max_length=16, verbose_name='estado')),
                ('admin_notes', models.TextField(blank=True, verbose_name='notas internas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'peticion de atencion',
                'verbose_name_plural': 'peticiones de atencion',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='HomeBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='nombre interno')),
                ('title', models.CharField(blank=True, max_length=180, verbose_name='titulo')),
                ('subtitle', models.CharField(blank=True, max_length=280, verbose_name='comentario')),
                ('eyebrow', models.CharField(blank=True, max_length=80, verbose_name='texto decorativo')),
                ('media_type', models.CharField(choices=[('image', 'Imagen'), ('video', 'Video corto')], default='image', max_length=10, verbose_name='tipo de medio')),
                ('layout', models.CharField(choices=[('editorial', 'Estilo actual'), ('flat', 'Imagen o video plano')], default='editorial', max_length=12, verbose_name='estilo')),
                ('media_url', models.CharField(help_text='Usa imagen o video MP4/WebM de hasta 10 segundos.', max_length=500, verbose_name='URL de imagen o video')),
                ('background_url', models.CharField(blank=True, default='assets/img/shape/1.webp', max_length=500, verbose_name='URL de fondo')),
                ('button_label', models.CharField(blank=True, max_length=60, verbose_name='texto del boton')),
                ('button_url', models.CharField(blank=True, help_text='Puede apuntar a una URL, seccion o video.', max_length=500, verbose_name='URL del boton')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='orden')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'banner del inicio',
                'verbose_name_plural': 'banners del inicio',
                'ordering': ('position', 'id'),
            },
        ),
        migrations.AddField(
            model_name='product',
            name='audience',
            field=models.CharField(choices=[('men', 'Hombre'), ('women', 'Mujer'), ('unisex', 'Unisex')], db_index=True, default='unisex', max_length=12, verbose_name='seccion'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('footwear', 'Calzado'), ('accessory', 'Accesorio')], db_index=True, default='footwear', max_length=12, verbose_name='tipo'),
        ),
        migrations.CreateModel(
            name='BlogComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, verbose_name='nombre')),
                ('email', models.EmailField(max_length=254, verbose_name='correo')),
                ('body', models.TextField(max_length=2000, verbose_name='comentario')),
                ('is_approved', models.BooleanField(db_index=True, default=False, verbose_name='aprobado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='store.blogpost')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'comentario del blog',
                'verbose_name_plural': 'comentarios del blog',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, verbose_name='nombre')),
                ('email', models.EmailField(max_length=254, verbose_name='correo')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='calificacion')),
                ('title', models.CharField(max_length=180, verbose_name='titulo')),
                ('body', models.TextField(max_length=2000, verbose_name='resena')),
                ('is_approved', models.BooleanField(db_index=True, default=False, verbose_name='aprobada')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='store.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'resena de producto',
                'verbose_name_plural': 'resenas de productos',
                'ordering': ('-created_at',),
            },
        ),
    ]
