# Generated by Django 5.2.16 on 2026-07-13 02:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_contactrequest_homebanner_product_audience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homebanner',
            name='media_file',
            field=models.FileField(blank=True, help_text='Puedes subir JPG, PNG, WebP, MP4 o WebM de hasta 10 segundos.', upload_to='marketing/banners/', validators=[django.core.validators.FileExtensionValidator(('jpg', 'jpeg', 'png', 'webp', 'mp4', 'webm'))], verbose_name='archivo de imagen o video'),
        ),
        migrations.AlterField(
            model_name='homebanner',
            name='media_url',
            field=models.CharField(blank=True, help_text='Alternativa al archivo: pega una URL o ruta existente.', max_length=500, verbose_name='URL de imagen o video'),
        ),
    ]
