# Generated by Django 5.2.16 on 2026-07-13 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_homebanner_media_file_alter_homebanner_media_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcomment',
            name='admin_response',
            field=models.TextField(blank=True, verbose_name='respuesta de Juaco Store'),
        ),
        migrations.AddField(
            model_name='blogcomment',
            name='responded_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='fecha de respuesta'),
        ),
        migrations.AddField(
            model_name='productreview',
            name='admin_response',
            field=models.TextField(blank=True, verbose_name='respuesta de Juaco Store'),
        ),
        migrations.AddField(
            model_name='productreview',
            name='responded_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='fecha de respuesta'),
        ),
    ]
