# Generated by Django 5.2.16 on 2026-07-13 02:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_blogcomment_admin_response_blogcomment_responded_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='store.blogcomment', verbose_name='respuesta a'),
        ),
        migrations.AddField(
            model_name='productreview',
            name='recommends',
            field=models.BooleanField(default=True, verbose_name='recomienda el producto'),
        ),
    ]
