# Generated by Django 5.2.16 on 2026-07-13 02:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_blogcomment_parent_productreview_recommends'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingPopup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='nombre interno')),
                ('title', models.CharField(max_length=180, verbose_name='titulo')),
                ('message', models.TextField(max_length=600, verbose_name='mensaje')),
                ('image_file', models.FileField(blank=True, upload_to='marketing/popups/', validators=[django.core.validators.FileExtensionValidator(('jpg', 'jpeg', 'png', 'webp'))], verbose_name='imagen')),
                ('image_url', models.CharField(blank=True, max_length=500, verbose_name='URL de imagen')),
                ('image_position', models.CharField(choices=[('left', 'Izquierda'), ('right', 'Derecha')], default='left', max_length=8, verbose_name='posicion de imagen')),
                ('button_label', models.CharField(max_length=60, verbose_name='texto del boton')),
                ('button_url', models.CharField(max_length=500, verbose_name='URL del boton')),
                ('delay_seconds', models.PositiveSmallIntegerField(default=2, help_text='Entre 0 y 30 segundos.', validators=[django.core.validators.MaxValueValidator(30)], verbose_name='espera antes de mostrar')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='prioridad')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'popup promocional',
                'verbose_name_plural': 'popups promocionales',
                'ordering': ('position', '-updated_at'),
            },
        ),
    ]
