# Generated by Django 5.2.16 on 2026-07-13 03:04

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_marketingpopup'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True, verbose_name='codigo')),
                ('discount_type', models.CharField(choices=[('percentage', 'Porcentaje'), ('fixed', 'Valor fijo')], default='percentage', max_length=12, verbose_name='tipo de descuento')),
                ('value', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='valor')),
                ('minimum_purchase', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='compra minima')),
                ('starts_at', models.DateTimeField(verbose_name='inicio de vigencia')),
                ('expires_at', models.DateTimeField(verbose_name='fecha de expiracion')),
                ('usage_limit', models.PositiveIntegerField(blank=True, null=True, verbose_name='limite total de usos')),
                ('times_used', models.PositiveIntegerField(default=0, editable=False, verbose_name='veces canjeado')),
                ('once_per_user', models.BooleanField(default=True, verbose_name='un uso por usuario')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'cupon',
                'verbose_name_plural': 'cupones',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='order',
            name='coupon_code',
            field=models.CharField(blank=True, max_length=40, verbose_name='codigo de cupon'),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='descuento'),
        ),
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='store.coupon', verbose_name='cupon'),
        ),
        migrations.CreateModel(
            name='CouponRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='descuento aplicado')),
                ('redeemed_at', models.DateTimeField(auto_now_add=True)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='redemptions', to='store.coupon')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_redemption', to='store.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coupon_redemptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'canje de cupon',
                'verbose_name_plural': 'canjes de cupones',
                'ordering': ('-redeemed_at',),
            },
        ),
    ]
