# Generated by Django 5.2.16 on 2026-07-13 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_product_additional_information_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='collection',
            field=models.CharField(blank=True, choices=[('classics', 'Clasicas'), ('urban', 'Urbanas'), ('sport', 'Deportivas'), ('limited', 'Edicion limitada')], db_index=True, max_length=16, verbose_name='coleccion'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(choices=[('Jordan', 'Jordan'), ('Adidas', 'Adidas'), ('Puma', 'Puma'), ('Nike', 'Nike')], max_length=40, verbose_name='marca'),
        ),
    ]
