# Generated by Django 5.2.16 on 2026-07-13 21:59

from django.db import migrations


def normalize_product_brands(apps, schema_editor):
    Product = apps.get_model("store", "Product")
    canonical_brands = {"jordan": "Jordan", "adidas": "Adidas", "puma": "Puma", "nike": "Nike"}
    for stored_value, canonical_value in canonical_brands.items():
        Product.objects.filter(brand__iexact=stored_value).update(brand=canonical_value)


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_product_catalog_assignments'),
    ]

    operations = [
        migrations.RunPython(normalize_product_brands, migrations.RunPython.noop),
    ]
