# Generated by Django 5.2.16 on 2026-07-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0022_normalize_product_brands"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsletterSubscription",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("email", models.EmailField(max_length=254, unique=True, verbose_name="correo electrónico")),
                ("is_active", models.BooleanField(default=True, verbose_name="suscripción activa")),
                ("subscribed_at", models.DateTimeField(auto_now_add=True, verbose_name="fecha de suscripción")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="última actualización")),
            ],
            options={
                "verbose_name": "suscripción al newsletter",
                "verbose_name_plural": "suscripciones al newsletter",
                "ordering": ("-subscribed_at",),
            },
        ),
    ]