# Generated by Django 5.2.16 on 2026-07-14

from django.db import migrations, models


def mark_existing_pickups(apps, schema_editor):
    Order = apps.get_model("store", "Order")
    Order.objects.filter(address_line_1__iexact="Recogida en tienda", city__iexact="Neiva").update(delivery_method="pickup")


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0023_newslettersubscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="delivery_method",
            field=models.CharField(choices=[("courier", "Domicilio"), ("pickup", "Recogida en Neiva")], default="courier", max_length=10, verbose_name="tipo de envío"),
        ),
        migrations.RunPython(mark_existing_pickups, migrations.RunPython.noop),
    ]