# Generated by Django 5.2.16 on 2026-08-01 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_product_release_date_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paid_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='fecha de pago'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_attempts',
            field=models.PositiveSmallIntegerField(default=0, editable=False, verbose_name='intentos de pago'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_reference',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=60, verbose_name='referencia de pago'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('PROCESSING', 'En proceso'), ('PENDING', 'Pendiente por el banco'), ('APPROVED', 'Aprobado'), ('REJECTED', 'Rechazado'), ('FAILED', 'Fallido'), ('VOIDED', 'Anulado'), ('NO_TRANSACTION_FOUND', 'Sin intentos de pago')], editable=False, max_length=24, verbose_name='estado del pago'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_transaction_id',
            field=models.CharField(blank=True, editable=False, max_length=80, verbose_name='transacción de la pasarela'),
        ),
    ]
