# Generated by Django 5.2.16 on 2026-08-01 02:33

from django.db import migrations, models


def mark_existing_orders_as_reserved(apps, schema_editor):
    """Los pedidos anteriores descontaron inventario al crearse, no al pagarse."""
    Order = apps.get_model("store", "Order")
    Order.objects.update(stock_reserved=True)


def unmark_orders(apps, schema_editor):
    Order = apps.get_model("store", "Order")
    Order.objects.update(stock_reserved=False)


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_order_paid_at_order_payment_attempts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='stock_reserved',
            field=models.BooleanField(default=False, editable=False, verbose_name='inventario descontado'),
        ),
        migrations.RunPython(mark_existing_orders_as_reserved, unmark_orders),
    ]
