# Generated by Django 5.2.16 on 2026-08-01 04:46

import django.core.validators
import store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_order_stock_reserved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homebanner',
            name='media_file',
            field=models.FileField(blank=True, help_text='Puedes subir JPG, PNG, WebP, MP4 o WebM de hasta 10 segundos.', upload_to='marketing/banners/', validators=[django.core.validators.FileExtensionValidator(('jpg', 'jpeg', 'png', 'webp', 'mp4', 'webm')), store.models.validate_uploaded_media], verbose_name='archivo de imagen o video'),
        ),
        migrations.AlterField(
            model_name='marketingpopup',
            name='image_file',
            field=models.FileField(blank=True, upload_to='marketing/popups/', validators=[django.core.validators.FileExtensionValidator(('jpg', 'jpeg', 'png', 'webp')), store.models.validate_uploaded_media], verbose_name='imagen'),
        ),
    ]
