# Generated by Django 5.2.16 on 2026-08-01 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0031_order_confirmation_email_sent_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_on_sale',
            field=models.BooleanField(db_index=True, default=False, help_text='Activa esta opcion para publicar el producto en la seccion Ofertas.', verbose_name='mostrar en Ofertas'),
        ),
    ]
