# Generated by Django 5.2.16 on 2026-08-01 22:44

import django.core.validators
import store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0032_product_is_on_sale'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, unique=True, verbose_name='título')),
                ('slug', models.SlugField(max_length=130, unique=True, verbose_name='identificador URL')),
                ('description', models.TextField(max_length=320, verbose_name='descripción')),
                ('banner_image_file', models.FileField(blank=True, help_text='Sube una imagen JPG, PNG o WebP. También puedes usar una URL en el campo siguiente.', upload_to='store/sections/banners/', validators=[django.core.validators.FileExtensionValidator(('jpg', 'jpeg', 'png', 'webp')), store.models.validate_uploaded_media], verbose_name='archivo del banner')),
                ('banner_image_url', models.CharField(blank=True, help_text='Alternativa al archivo: pega una URL o ruta existente.', max_length=500, verbose_name='URL del banner')),
                ('banner_image_alt', models.CharField(blank=True, max_length=180, verbose_name='texto alternativo del banner')),
                ('empty_image_file', models.FileField(blank=True, help_text='Imagen editorial que se muestra cuando la sección no tiene productos.', upload_to='store/sections/empty/', validators=[django.core.validators.FileExtensionValidator(('jpg', 'jpeg', 'png', 'webp')), store.models.validate_uploaded_media], verbose_name='archivo de estado vacío')),
                ('empty_image_url', models.CharField(blank=True, help_text='Alternativa al archivo: pega una URL o ruta existente.', max_length=500, verbose_name='URL de estado vacío')),
                ('empty_image_alt', models.CharField(blank=True, max_length=180, verbose_name='texto alternativo de estado vacío')),
                ('empty_title', models.CharField(blank=True, help_text='Si lo dejas vacío se generará automáticamente con el nombre de la sección.', max_length=180, verbose_name='título de estado vacío')),
                ('empty_description', models.TextField(blank=True, help_text='Mensaje opcional que acompaña la imagen cuando todavía no hay productos.', max_length=320, verbose_name='descripción de estado vacío')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='orden en Tienda')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='visible en la tienda')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'sección de la tienda',
                'verbose_name_plural': 'secciones de la tienda',
                'ordering': ('position', 'title', 'id'),
            },
        ),
        migrations.AddField(
            model_name='product',
            name='store_sections',
            field=models.ManyToManyField(blank=True, help_text='Selecciona una o varias secciones dinámicas en las que debe aparecer el producto.', related_name='products', to='store.storesection', verbose_name='secciones personalizadas de Tienda'),
        ),
    ]
