# Generated by Django 5.2.16 on 2026-08-07 00:54

import django.core.validators
import django.db.models.deletion
import store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0037_order_operations'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_file',
            field=models.FileField(blank=True, help_text='Se redimensiona y convierte automáticamente a WebP.', upload_to='products/main/', validators=[django.core.validators.FileExtensionValidator(('jpg', 'jpeg', 'png', 'webp')), store.models.validate_uploaded_media], verbose_name='archivo de imagen principal'),
        ),
        migrations.AlterField(
            model_name='homebanner',
            name='media_file',
            field=models.FileField(blank=True, help_text='Las imágenes se redimensionan y convierten a WebP. También puedes subir MP4 o WebM de hasta 10 segundos.', upload_to='marketing/banners/', validators=[django.core.validators.FileExtensionValidator(('jpg', 'jpeg', 'png', 'webp', 'mp4', 'webm')), store.models.validate_uploaded_media], verbose_name='archivo de imagen o video'),
        ),
        migrations.AlterField(
            model_name='marketingpopup',
            name='image_file',
            field=models.FileField(blank=True, help_text='Se redimensiona y convierte automáticamente a WebP.', upload_to='marketing/popups/', validators=[django.core.validators.FileExtensionValidator(('jpg', 'jpeg', 'png', 'webp')), store.models.validate_uploaded_media], verbose_name='imagen'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.CharField(blank=True, help_text='Alternativa al archivo subido para imágenes externas o heredadas.', max_length=255, verbose_name='URL o ruta de imagen principal'),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', models.FileField(help_text='Se redimensiona y convierte automáticamente a WebP.', upload_to='products/gallery/', validators=[django.core.validators.FileExtensionValidator(('jpg', 'jpeg', 'png', 'webp')), store.models.validate_uploaded_media], verbose_name='archivo')),
                ('image_alt', models.CharField(blank=True, max_length=180, verbose_name='texto alternativo')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='orden')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_images', to='store.product', verbose_name='producto')),
            ],
            options={
                'verbose_name': 'imagen de producto',
                'verbose_name_plural': 'imágenes de producto',
                'ordering': ('position', 'id'),
            },
        ),
    ]
