# Generated by Django 6.0.1 on 2026-08-08 23:31

import django.core.validators
import django.db.models.functions.text
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0038_product_image_file_alter_homebanner_media_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='minimum_purchase',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='compra minima'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='usage_limit',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='limite total de usos'),
        ),
        migrations.AddConstraint(
            model_name='coupon',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('code'), name='unique_coupon_code_ci'),
        ),
        migrations.AddConstraint(
            model_name='coupon',
            constraint=models.CheckConstraint(condition=models.Q(('minimum_purchase__gte', 0)), name='coupon_minimum_purchase_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='coupon',
            constraint=models.CheckConstraint(condition=models.Q(('value__gt', 0)), name='coupon_value_positive'),
        ),
        migrations.AddConstraint(
            model_name='coupon',
            constraint=models.CheckConstraint(condition=models.Q(('discount_type', 'fixed'), ('value__lte', 100), _connector='OR'), name='coupon_percentage_at_most_100'),
        ),
        migrations.AddConstraint(
            model_name='coupon',
            constraint=models.CheckConstraint(condition=models.Q(('expires_at__gt', models.F('starts_at'))), name='coupon_expiry_after_start'),
        ),
        migrations.AddConstraint(
            model_name='coupon',
            constraint=models.CheckConstraint(condition=models.Q(('usage_limit__isnull', True), ('usage_limit__gte', 1), _connector='OR'), name='coupon_usage_limit_positive'),
        ),
        migrations.AddConstraint(
            model_name='coupon',
            constraint=models.CheckConstraint(condition=models.Q(('usage_limit__isnull', True), ('usage_limit__gte', models.F('times_used')), _connector='OR'), name='coupon_usage_not_over_limit'),
        ),
    ]
