# Generated by Django 6.0.1 on 2026-08-09 23:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0039_secure_coupon_integrity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='color_hex',
            field=models.CharField(blank=True, help_text='Opcional: si escribes un color y lo dejas vacío, se usará #505050 por defecto.', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$', 'Usa un color hexadecimal como #505050.')], verbose_name='código de color'),
        ),
    ]
