# Generated by Django 6.0.1 on 2026-08-10 02:04

import django.core.validators
import store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0040_alter_productvariant_color_hex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketingpopup',
            name='image_file',
            field=models.FileField(blank=True, help_text='Las imágenes se redimensionan y convierten a WebP. También puedes subir un MP4 o WebM corto.', upload_to='marketing/popups/', validators=[django.core.validators.FileExtensionValidator(('jpg', 'jpeg', 'png', 'webp', 'mp4', 'webm')), store.models.validate_uploaded_media], verbose_name='imagen o video'),
        ),
        migrations.AlterField(
            model_name='marketingpopup',
            name='image_url',
            field=models.CharField(blank=True, max_length=500, verbose_name='URL de imagen o video'),
        ),
    ]
